// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTe_t-4ivFEcQfGRcxaLD-h9uBbdvAKU',
    appId: '1:777258421525:web:1dcf6a378ae6bd5e322d1c',
    messagingSenderId: '777258421525',
    projectId: 'store-project-b9345',
    authDomain: 'store-project-b9345.firebaseapp.com',
    storageBucket: 'store-project-b9345.firebasestorage.app',
    measurementId: 'G-DKX9T5SW8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHx-oZaLxVyTQz3jUwcv0RfPPhHLAlUeY',
    appId: '1:777258421525:android:1ce3648a0cbfdc94322d1c',
    messagingSenderId: '777258421525',
    projectId: 'store-project-b9345',
    storageBucket: 'store-project-b9345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-bKLkHuo-7mpiFKoxq59rvI1KqU58N4Q',
    appId: '1:777258421525:ios:fb658d7c11e07aa9322d1c',
    messagingSenderId: '777258421525',
    projectId: 'store-project-b9345',
    storageBucket: 'store-project-b9345.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-bKLkHuo-7mpiFKoxq59rvI1KqU58N4Q',
    appId: '1:777258421525:ios:fb658d7c11e07aa9322d1c',
    messagingSenderId: '777258421525',
    projectId: 'store-project-b9345',
    storageBucket: 'store-project-b9345.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzTe_t-4ivFEcQfGRcxaLD-h9uBbdvAKU',
    appId: '1:777258421525:web:776bcfa0fa814164322d1c',
    messagingSenderId: '777258421525',
    projectId: 'store-project-b9345',
    authDomain: 'store-project-b9345.firebaseapp.com',
    storageBucket: 'store-project-b9345.firebasestorage.app',
    measurementId: 'G-LJBRX4Z0C0',
  );

}