// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4HQSCQZ2_WdhE2cgMiKDGjDxS57RMMcQ',
    appId: '1:470730509448:web:50539628375c590e41e33d',
    messagingSenderId: '470730509448',
    projectId: 'doandidongdxh',
    authDomain: 'doandidongdxh.firebaseapp.com',
    storageBucket: 'doandidongdxh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyQTneajOJoGnn3BiuCDmKKC9_xiicJ0',
    appId: '1:470730509448:android:7ab007f57b49135041e33d',
    messagingSenderId: '470730509448',
    projectId: 'doandidongdxh',
    storageBucket: 'doandidongdxh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt45LL4xcNP1r-xrnxry5XYXR_BNwqszI',
    appId: '1:470730509448:ios:78a13b6039e2361841e33d',
    messagingSenderId: '470730509448',
    projectId: 'doandidongdxh',
    storageBucket: 'doandidongdxh.appspot.com',
    androidClientId: '470730509448-0obieec9hfd8orhkrdks81l0kg3gr96h.apps.googleusercontent.com',
    iosClientId: '470730509448-p018hlc0l1mj8ogjubrlbjvgqlpkcl04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt45LL4xcNP1r-xrnxry5XYXR_BNwqszI',
    appId: '1:470730509448:ios:7afcf8b95f607d2241e33d',
    messagingSenderId: '470730509448',
    projectId: 'doandidongdxh',
    storageBucket: 'doandidongdxh.appspot.com',
    androidClientId: '470730509448-0obieec9hfd8orhkrdks81l0kg3gr96h.apps.googleusercontent.com',
    iosClientId: '470730509448-4ivq689o47gqqo86glflpulgfmfcpf3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
